// Copyright (c) 2026, The Discrete developers
//
// This file is part of Discrete.
//
// KAT-based tests for the PQ Phase 1 domain-separated derivations (spec §6/§8).
// The pinned expected values are mirrored in tests/pq/kat_vectors.json — that
// file is the published artifact other implementations test against. A mismatch
// between independent implementations is a chain split (spec §14), so these
// vectors must never change once shipped.
//
// Fixed inputs are generated by pat<N>(a,b)[i] = (i*a + b) mod 256, documented
// alongside each vector in kat_vectors.json.

#include "gtest/gtest.h"

#include "crypto_pq/PqDerive.h"

#include <array>
#include <cstdint>
#include <cstring>
#include <string>
#include <vector>

using namespace CryptoPQ;

namespace {

std::string to_hex(const uint8_t* d, std::size_t n) {
    static const char* h = "0123456789abcdef";
    std::string o;
    o.reserve(2 * n);
    for (std::size_t i = 0; i < n; ++i) { o += h[d[i] >> 4]; o += h[d[i] & 0xf]; }
    return o;
}
template <std::size_t N> std::string to_hex(const std::array<uint8_t, N>& a) {
    return to_hex(a.data(), N);
}

// pat<N>(a,b)[i] = (i*a + b) mod 256 — deterministic filler for fixed inputs.
template <std::size_t N> std::array<uint8_t, N> pat(uint8_t a, uint8_t b) {
    std::array<uint8_t, N> r;
    for (std::size_t i = 0; i < N; ++i) r[i] = static_cast<uint8_t>(i * a + b);
    return r;
}

std::vector<InputRef> fixedInputs() {
    std::vector<InputRef> ins(2);
    ins[0].prevTxid = pat<32>(1, 0);   ins[0].prevOutIndex = 7;
    ins[1].prevTxid = pat<32>(255, 5); ins[1].prevOutIndex = 0x01020304;
    return ins;
}

}  // namespace

// ===========================================================================
// KAT vectors — must equal tests/pq/kat_vectors.json
// ===========================================================================

TEST(PqDerive, InputsHash) {
    EXPECT_EQ(to_hex(inputsHash(fixedInputs())),
              "b48fdcb804a368c257fd9fa500023cda6dd9013da90b6c2f8186bda6e85a7d9b");
}

TEST(PqDerive, OutContext) {
    // outContext-v2: T is NOT part of the context (see PqDerive.h). Only
    // inputsHash, kemCt, and outputIndex feed the hash.
    Hash256 ih = inputsHash(fixedInputs());
    KemCiphertext kemCt = pat<1088>(7, 3);
    EXPECT_EQ(to_hex(outContext(ih, kemCt, 1)),
              "f565b6181ad5bbdb55fb7594b23355aac1e388324fd9ced017680474a4a87ede");
}

TEST(PqDerive, OutContextIndexIsolation) {
    Hash256 ih = inputsHash(fixedInputs());
    KemCiphertext kemCt = pat<1088>(7, 3);
    // Two different output indices must produce different outContext hashes
    // (this is what actually keeps two outputs of the same tx from colliding
    // now that T is no longer part of the context — see PqDerive.h).
    Hash256 oc0 = outContext(ih, kemCt, 1);
    Hash256 oc1 = outContext(ih, kemCt, 2);
    EXPECT_NE(oc0, oc1);
}

TEST(PqDerive, LegacyOutContextV1) {
    // Legacy (pre-v2) formula: T=0 appended as LE64 after outputIndex. Every
    // output minted before the outContext-v2 activation used this, always at
    // T=0. This value MUST NOT change — it is a receiver-side fallback for
    // outputs already on chain.
    Hash256 ih = inputsHash(fixedInputs());
    KemCiphertext kemCt = pat<1088>(7, 3);
    EXPECT_EQ(to_hex(legacyOutContextV1(ih, kemCt, 1, 0)),
              "32cfc3d894c9c87a8d5f7ca9b0dfc69760b39f3c267b7e7cdd41c8f65492fb1b");
}

TEST(PqDerive, LegacyOutContextV1TIsolation) {
    Hash256 ih = inputsHash(fixedInputs());
    KemCiphertext kemCt = pat<1088>(7, 3);
    // Two different T values must produce different legacy outContext hashes.
    Hash256 oc0 = legacyOutContextV1(ih, kemCt, 1, 0);
    Hash256 oc1 = legacyOutContextV1(ih, kemCt, 1, 1);
    EXPECT_NE(oc0, oc1);
    Hash256 oc2 = legacyOutContextV1(ih, kemCt, 1, 0xFFFFFFFFFFFFFFFFull);
    EXPECT_NE(oc0, oc2);
    EXPECT_NE(oc1, oc2);
}

TEST(PqDerive, OutContextV2DiffersFromLegacy) {
    // Same (inputsHash, kemCt, outputIndex) — different domain tag must still
    // produce a different hash, so a v2 context can never collide with a
    // legacy T=0 context.
    Hash256 ih = inputsHash(fixedInputs());
    KemCiphertext kemCt = pat<1088>(7, 3);
    EXPECT_NE(outContext(ih, kemCt, 1), legacyOutContextV1(ih, kemCt, 1, 0));
}

TEST(PqDerive, AeadKey) {
    Hash256 ih = inputsHash(fixedInputs());
    Hash256 oc = outContext(ih, pat<1088>(7, 3), 1);  // v2
    KemShared ss = pat<32>(1, 0);
    EXPECT_EQ(to_hex(deriveAeadKey(ss, oc)),
              "2bd2b59ab199533add5d1d65b305ebb5409221ef2634259d34af6b43d4f84cf1");
}

TEST(PqDerive, LegacyAeadKey) {
    // Cross-check against the published legacy PqDerive KAT (out_context above).
    Hash256 ih = inputsHash(fixedInputs());
    Hash256 oc = legacyOutContextV1(ih, pat<1088>(7, 3), 1, 0);
    KemShared ss = pat<32>(1, 0);
    EXPECT_EQ(to_hex(deriveAeadKey(ss, oc)),
              "933dac581886ce415e06756358cf6fc60e6c9f2f8bd9574e25e2af912171f680");
}

TEST(PqDerive, SpendCommit) {
    DsaPublicKey pk = pat<1952>(5, 1);
    Rho rho = pat<32>(3, 9);
    EXPECT_EQ(to_hex(spendCommit(pk, rho)),
              "0efa5a91ce3a6df44730c7d0cbebbc3d3896264f6826991914bac993684a151a");
}

TEST(PqDerive, Nullifier) {
    DsaPublicKey pk = pat<1952>(5, 1);
    Rho rho = pat<32>(3, 9);
    Hash256 prevTxid = pat<32>(1, 0);
    EXPECT_EQ(to_hex(nullifier(pk, rho, prevTxid, 7)),
              "94e9b820f5cd5da4d39a0a0855fe9d317fdec71228d922ba8a17799e8d64278e");
}

TEST(PqDerive, NullifierBindsOutpoint) {
    // Same (pk, rho) but different outpoints -> distinct nullifiers (a public rho
    // cannot be replayed into a colliding output).
    DsaPublicKey pk = pat<1952>(5, 1);
    Rho rho = pat<32>(3, 9);
    Hash256 txA = pat<32>(1, 0);
    Hash256 txB = pat<32>(2, 0);
    EXPECT_NE(nullifier(pk, rho, txA, 7), nullifier(pk, rho, txB, 7));
    EXPECT_NE(nullifier(pk, rho, txA, 7), nullifier(pk, rho, txA, 8));
}

TEST(PqDerive, SpendCommitAndNullifierDiffer) {
    // Same (pk, rho), different domain -> distinct outputs.
    DsaPublicKey pk = pat<1952>(5, 1);
    Rho rho = pat<32>(3, 9);
    EXPECT_NE(spendCommit(pk, rho), nullifier(pk, rho, pat<32>(1, 0), 7));
}

TEST(PqDerive, TxSigningDigest) {
    DsaPublicKey pk = pat<1952>(5, 1);
    Rho rho = pat<32>(3, 9);
    Hash256 ih = inputsHash(fixedInputs());
    Hash256 oc = outContext(ih, pat<1088>(7, 3), 1);
    Hash256 sc = spendCommit(pk, rho);

    UnsignedTx tx;
    tx.version = 1;  // TRANSACTION_VERSION_1
    tx.fee = 12345;

    DigestInput di;
    di.prevTxid = pat<32>(1, 0);
    di.prevOutIndex = 7;
    di.authPub = pk;
    di.rhoReveal = rho;
    tx.inputs.push_back(di);

    DigestOutput out;
    out.type = 0x10;
    out.amount = 1000000;
    out.kemCt = pat<1088>(7, 3);
    out.encPayload = pat<56>(2, 1);
    out.spendCommit = sc;
    tx.outputs.push_back(out);

    EXPECT_EQ(to_hex(txSigningDigest(tx)),
              "02de2e91449a463ae7dc71adde97eeab211a7a1ecbd22e1b0c3232348d5ebbd3");
}

TEST(PqDerive, TxSigningDigestIsTamperSensitive) {
    DsaPublicKey pk = pat<1952>(5, 1);
    Rho rho = pat<32>(3, 9);

    UnsignedTx tx;
    tx.version = 1;  // TRANSACTION_VERSION_1
    tx.fee = 12345;
    DigestInput di; di.prevTxid = pat<32>(1, 0); di.prevOutIndex = 7;
    di.authPub = pk; di.rhoReveal = rho;
    tx.inputs.push_back(di);
    DigestOutput out; out.type = 0x10; out.amount = 1000000;
    out.kemCt = pat<1088>(7, 3); out.encPayload = pat<56>(2, 1);
    out.spendCommit = spendCommit(pk, rho);
    tx.outputs.push_back(out);

    Hash256 base = txSigningDigest(tx);

    UnsignedTx t2 = tx;
    t2.fee += 1;  // flip the fee
    EXPECT_NE(base, txSigningDigest(t2));

    UnsignedTx t3 = tx;
    t3.outputs[0].amount += 1;  // flip an output amount
    EXPECT_NE(base, txSigningDigest(t3));

    // The digest must also bind the prefix fields that the txid covers but the
    // draft §8.1 omitted: txType, unlockHeight, and extra. Otherwise a relayer
    // could mutate them without invalidating the signature.
    UnsignedTx t4 = tx; t4.txType = 2;  // 0x02: reserved/unknown subtype
    EXPECT_NE(base, txSigningDigest(t4));

    UnsignedTx t5 = tx; t5.unlockHeight = 1;
    EXPECT_NE(base, txSigningDigest(t5));

    UnsignedTx t6 = tx; t6.extra = {0x01, 0x02, 0x03};
    EXPECT_NE(base, txSigningDigest(t6));

    // Per-output unlockHeight is consensus and must be bound too — otherwise a
    // relayer could change an output's spend lock without invalidating the sig.
    UnsignedTx t7 = tx; t7.outputs[0].unlockHeight = 1;
    EXPECT_NE(base, txSigningDigest(t7));
}

// ===========================================================================
// Reserved-namespace guard (spec plan §2 item 8): no v4-plain derivation may
// reuse the Phase-2 KDSK-CT mask domain.
// ===========================================================================

TEST(PqDerive, ReservedCtMaskNamespaceUnused) {
    const std::string reserved = kReservedCtMask;
    const char* used[] = {
        kDomainInputsHash, kDomainOutContext, kDomainAeadKey,
        kDomainSpendCommit, kDomainNullifier, kDomainTxSign,
    };
    for (const char* tag : used) {
        EXPECT_NE(std::string(tag), reserved);
    }
}

// Phase 3 shielded-serial domain: same guard, one tier up. The serial shares the
// unified spent-marker set with Phase-1 nullifiers, so domain separation is the
// only thing keeping a serial from being valid as a plain nullifier.
TEST(PqDerive, ReservedShieldedSerialNamespaceUnused) {
    const std::string reserved = kReservedShieldedSerial;
    const char* used[] = {
        kDomainInputsHash, kDomainOutContext, kDomainAeadKey,
        kDomainSpendCommit, kDomainNullifier, kDomainTxSign,
        kReservedCtMask,
    };
    for (const char* tag : used) {
        EXPECT_NE(std::string(tag), reserved);
    }
}

int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
