// Copyright (c) 2026, The Discrete developers
//
// This file is part of Discrete.
//
// Cross-implementation KAT for the 25-word recovery phrase.
//
// A Discrete master seed is 32 raw bytes and the phrase is its only human
// transport, so the web wallet's encoder and this one must agree byte for byte
// or a user restoring a web-wallet phrase in simplewallet/walletd/zedwallet
// lands on a different, empty identity with no diagnostic.
//
// The expected phrases below were produced by the *shipped web wallet code*
// (discrete-webwallet src/model/Mnemonic.js + MnemonicLang.js driven directly),
// not by a reimplementation of the algorithm here. Treat them as frozen: a
// mismatch means one of the two implementations changed and phrases minted by
// the other stop restoring.
//
// Seeds use pat(a,b)[i] = (i*a + b) mod 256, the filler convention from
// test_pq_derive.cpp, plus the two extremes and one seed whose high byte is
// above 0x10 -- not a reducible Ed25519 scalar, so it could never have come out
// of the legacy CryptoNote encoder. That case is what proves nothing on this
// path still normalizes the seed.

#include "gtest/gtest.h"

#include "Mnemonics/electrum-words.h"

#include <sstream>
#include <string>
#include <vector>

namespace {

const char* const kLanguage = "English";

std::string toHex(const Crypto::SecretKey& key) {
  static const char* h = "0123456789abcdef";
  std::string out;
  out.reserve(2 * sizeof(key.data));
  for (std::size_t i = 0; i < sizeof(key.data); ++i) {
    const uint8_t b = static_cast<uint8_t>(key.data[i]);
    out += h[b >> 4];
    out += h[b & 0xf];
  }
  return out;
}

struct Vector {
  const char* name;
  const char* seedHex;
  const char* words;
};

// FROZEN -- generated by the web wallet's own Mnemonic.mn_encode.
const Vector kVectors[] = {
  {"pat(1,0)",
   "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
   "amaze buffet cake entrance symptoms tiger lamb maze nestle python dusted "
   "faxed update vague zinger boxes ornament renting glass gained island "
   "nabbing afield calamity boxes"},
  {"pat(7,3)",
   "030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dc",
   "volcano pliers second keyboard nagged segments woken joking seismic lilac "
   "glass semifinal acoustic eavesdrop sequence maximum bowling serving "
   "altitude adopt setup myriad upbeat sewage segments"},
  {"all-zero",
   "0000000000000000000000000000000000000000000000000000000000000000",
   "abbey abbey abbey abbey abbey abbey abbey abbey abbey abbey abbey abbey "
   "abbey abbey abbey abbey abbey abbey abbey abbey abbey abbey abbey abbey "
   "abbey"},
  {"all-ff",
   "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
   "foamy solved soggy foamy solved soggy foamy solved soggy foamy solved "
   "soggy foamy solved soggy foamy solved soggy foamy solved soggy foamy "
   "solved soggy soggy"},
  // High byte 0xff > 0x10: unreachable for a reduced Ed25519 scalar.
  {"high-byte",
   "00000000000000000000000000000000000000000000000000000000000000ff",
   "abbey abbey abbey abbey abbey abbey abbey abbey abbey abbey abbey abbey "
   "abbey abbey abbey abbey abbey abbey abbey abbey abbey dotted habitat "
   "gumball abbey"},
};

// A valid phrase to mutate in the rejection tests.
const char* const kValidPhrase = kVectors[0].words;

std::vector<std::string> split(const std::string& phrase) {
  std::vector<std::string> words;
  std::string current;
  for (char c : phrase) {
    if (c == ' ') {
      if (!current.empty()) { words.push_back(current); current.clear(); }
    } else {
      current += c;
    }
  }
  if (!current.empty()) words.push_back(current);
  return words;
}

std::string join(const std::vector<std::string>& words) {
  std::string out;
  for (std::size_t i = 0; i < words.size(); ++i) {
    if (i != 0) out += ' ';
    out += words[i];
  }
  return out;
}

}  // namespace

// The seed the web wallet encodes and the seed we decode are the same bytes,
// and our encoder emits the same words. Both directions, every vector.
TEST(MnemonicCompat, WebwalletVectorsAgreeBothDirections) {
  for (const Vector& v : kVectors) {
    SCOPED_TRACE(v.name);

    Crypto::SecretKey decoded;
    std::string language;
    ASSERT_TRUE(Crypto::ElectrumWords::words_to_bytes(v.words, decoded, language))
        << "web wallet phrase rejected";
    EXPECT_EQ(std::string(v.seedHex), toHex(decoded));
    EXPECT_EQ(std::string(kLanguage), language);

    std::string encoded;
    ASSERT_TRUE(Crypto::ElectrumWords::bytes_to_words(decoded, encoded, kLanguage));
    EXPECT_EQ(std::string(v.words), encoded);
  }
}

// simplewallet's export_keys writes the phrase as a padded 5-column grid, so a
// pasted backup carries newlines and runs of spaces. Splitting on ' ' alone made
// the wallet's own backup unreadable by --mnemonic-seed.
TEST(MnemonicCompat, AcceptsPhraseFormattedAsAKeyBackup) {
  const std::vector<std::string> words = split(kValidPhrase);
  ASSERT_EQ(25u, words.size());

  std::string grid = "\n ";
  for (std::size_t i = 0; i < words.size(); ++i) {
    grid += words[i];
    grid += "   ";  // seedFormater pads each column
    if ((i + 1) % 5 == 0) grid += "\n ";
  }
  grid += "\n";

  Crypto::SecretKey decoded;
  std::string language;
  ASSERT_TRUE(Crypto::ElectrumWords::words_to_bytes(grid, decoded, language));
  EXPECT_EQ(std::string(kVectors[0].seedHex), toHex(decoded));

  // Tabs and CRLF too -- phrases also arrive pasted out of a browser or chat.
  std::string mixed;
  for (std::size_t i = 0; i < words.size(); ++i) {
    if (i != 0) mixed += (i % 3 == 0) ? "\r\n" : ((i % 2 == 0) ? "\t" : "  ");
    mixed += words[i];
  }
  Crypto::SecretKey fromMixed;
  ASSERT_TRUE(Crypto::ElectrumWords::words_to_bytes(mixed, fromMixed, language));
  EXPECT_EQ(std::string(kVectors[0].seedHex), toHex(fromMixed));
}

// 12 words carry 16 bytes. The Electrum-compatible path used to duplicate them
// into the upper half, minting a 128-bit master seed with no warning. There is
// no legitimate 12-word Discrete seed, so this must fail closed.
TEST(MnemonicCompat, RejectsTwelveWordSeed) {
  std::vector<std::string> words = split(kValidPhrase);
  words.resize(12);

  Crypto::SecretKey decoded;
  std::string language;
  EXPECT_FALSE(Crypto::ElectrumWords::words_to_bytes(join(words), decoded, language));
}

// 24 words carry the whole seed but no checksum word, so a phrase that lost its
// last word to a copy-paste would restore a valid-looking, different wallet.
TEST(MnemonicCompat, RejectsTwentyFourWordSeedWithNoChecksum) {
  std::vector<std::string> words = split(kValidPhrase);
  words.resize(24);

  Crypto::SecretKey decoded;
  std::string language;
  EXPECT_FALSE(Crypto::ElectrumWords::words_to_bytes(join(words), decoded, language));
}

// The checksum word is the only typo protection the phrase has; it has to bite.
TEST(MnemonicCompat, RejectsWrongChecksumWord) {
  std::vector<std::string> words = split(kValidPhrase);
  ASSERT_EQ(std::string("boxes"), words[24]);
  words[24] = "abbey";  // a real word, wrong position

  Crypto::SecretKey decoded;
  std::string language;
  EXPECT_FALSE(Crypto::ElectrumWords::words_to_bytes(join(words), decoded, language));
}

// A word swapped for another real word keeps every word in the dictionary, so
// only the checksum can catch it.
TEST(MnemonicCompat, RejectsTransposedWords) {
  std::vector<std::string> words = split(kValidPhrase);
  std::swap(words[3], words[4]);

  Crypto::SecretKey decoded;
  std::string language;
  EXPECT_FALSE(Crypto::ElectrumWords::words_to_bytes(join(words), decoded, language));
}

TEST(MnemonicCompat, RejectsEmptyAndNonWords) {
  Crypto::SecretKey decoded;
  std::string language;

  EXPECT_FALSE(Crypto::ElectrumWords::words_to_bytes("", decoded, language));
  EXPECT_FALSE(Crypto::ElectrumWords::words_to_bytes("   \n\t ", decoded, language));

  std::vector<std::string> words = split(kValidPhrase);
  words[0] = "notaword";
  EXPECT_FALSE(Crypto::ElectrumWords::words_to_bytes(join(words), decoded, language));
}

// The import prompt calls is_valid_mnemonic in a retry loop. A phrase of exactly
// 25 words passes the length gate and, if it then fails to decode, reaches the
// diagnostic that lists which words are not in the dictionary. That path used to
// read the word list through a null Language::Base and take the wallet down, so
// a single mistyped word ended the session instead of re-prompting.
TEST(MnemonicCompat, InvalidTwentyFiveWordPhraseReportsInsteadOfCrashing) {
  std::vector<std::string> words = split(kValidPhrase);
  words[0] = "notaword";
  ASSERT_EQ(25u, words.size());

  Crypto::SecretKey decoded;
  std::ostringstream out;
  EXPECT_FALSE(Crypto::ElectrumWords::is_valid_mnemonic(join(words), decoded, out));

  // The rejected word is named, which is the whole point of the diagnostic.
  EXPECT_NE(std::string::npos, out.str().find("notaword"));
}

TEST(MnemonicCompat, EveryWordUnknownIsAlsoReported) {
  std::vector<std::string> words(25, "zzzznotaword");

  Crypto::SecretKey decoded;
  std::ostringstream out;
  EXPECT_FALSE(Crypto::ElectrumWords::is_valid_mnemonic(join(words), decoded, out));
  EXPECT_NE(std::string::npos, out.str().find("zzzznotaword"));
}

TEST(MnemonicCompat, ValidPhraseStillPassesTheFrontEndCheck) {
  Crypto::SecretKey decoded;
  std::ostringstream out;
  EXPECT_TRUE(Crypto::ElectrumWords::is_valid_mnemonic(kValidPhrase, decoded, out));
}

TEST(MnemonicCompat, EnglishWordListIsPopulated) {
  EXPECT_EQ(1626u, Crypto::ElectrumWords::english_word_list().size());
}

int main(int argc, char** argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
