"""Build one explicit immutable profile offline with Anza platform-tools 1.57.

Output must be a new directory. No keypair is read or generated; no RPC is used.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import struct
import subprocess

from profile import decode_key, make_profile

ROOT = Path(__file__).resolve().parent
INPUTS = ('Cargo.toml', 'Cargo.lock', 'src/lib.rs', 'src/profile.rs', 'profile.py', 'build.py')


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--network', required=True, choices=('mainnet-usdc', 'devnet-usdc', 'local-synthetic'))
    parser.add_argument('--program-id', required=True, help='Public key from the separately held deployment keypair')
    parser.add_argument('--genesis-hash', required=True, help='Independently pinned intended chain identity')
    parser.add_argument('--local-mint', help='Only for local-synthetic')
    parser.add_argument('--tools-root', required=True, type=Path)
    parser.add_argument('--cargo-home', required=True, type=Path, help='Writable offline dependency cache, not frozen evidence')
    parser.add_argument('--output', required=True, type=Path)
    args = parser.parse_args()
    profile = make_profile(args.network, args.program_id, args.genesis_hash, args.local_mint)
    output = args.output.resolve()
    if output.exists():
        parser.error('Output already exists; use a fresh directory to preserve build evidence')
    tools = args.tools_root.resolve()
    ext = '.exe' if os.name == 'nt' else ''
    cargo = tools / 'rust/bin' / ('cargo' + ext)
    rustc = tools / 'rust/bin' / ('rustc' + ext)
    version = subprocess.check_output([str(rustc), '--version', '--verbose'], text=True)
    if 'ae660768afd467d131776918a1627e18920b230c' not in version:
        parser.error('Expected the reviewed Anza platform-tools 1.57 rustc commit')
    output.mkdir(parents=True)
    source = output / 'source'
    (source / 'src').mkdir(parents=True)
    for item in ('Cargo.toml', 'Cargo.lock', 'src/lib.rs'):
        shutil.copyfile(ROOT / item, source / item)
    generated = '// Generated by build.py; the selected keys are immutable in this ELF.\n'
    for name, value in (('PROGRAM_ID', profile['program_id']), ('MINT_ID', profile['mint'])):
        generated += f'const {name}: [u8; 32] = {list(decode_key(value))};\n'
    (source / 'src/profile.rs').write_bytes(generated.encode('ascii'))
    env = os.environ.copy()
    env.update(CARGO_HOME=args.cargo_home.resolve().as_posix(), RUSTC=rustc.as_posix(),
               CARGO_BUILD_JOBS='1', RUSTFLAGS='', CARGO_ENCODED_RUSTFLAGS='')
    command = [str(cargo), 'build', '--offline', '--locked', '--target', 'sbpfv3-solana-solana',
               '--release', '--target-dir', str(output / 'target')]
    with (output / 'build.log').open('wb') as log:
        result = subprocess.run(command, cwd=source, env=env, stdout=log, stderr=subprocess.STDOUT)
    if result.returncode:
        raise SystemExit(f'Build failed ({result.returncode}); retained log: {output / "build.log"}')
    artifact = output / 'target/sbpfv3-solana-solana/release/xds_swap_sbpfv3.so'
    data = artifact.read_bytes()
    if len(data) < 64 or data[:6] != b'\x7fELF\x02\x01' or struct.unpack_from('<I', data, 48)[0] != 3:
        raise SystemExit('Expected ELF64 little-endian SBPFv3')
    shutil.copyfile(artifact, output / 'solana_escrow.so')
    manifest = {'schema': 1, 'profile': profile,
                'artifact': {'file': 'solana_escrow.so', 'bytes': len(data), 'sha256': sha(artifact), 'sbpf_version': 3},
                'source_sha256': {name: sha(ROOT / name) for name in INPUTS},
                'compiled_source_sha256': {name: sha(source / name) for name in ('Cargo.toml', 'Cargo.lock', 'src/lib.rs', 'src/profile.rs')},
                'toolchain': {'provider': 'Anza platform-tools 1.57', 'rustc_version': version.strip(),
                              'cargo_sha256': sha(cargo), 'rustc_sha256': sha(rustc)},
                'command': command, 'scope': 'Offline build only; no deployment, token transfer or chain qualification'}
    (output / 'build-manifest.json').write_bytes((json.dumps(manifest, indent=2) + '\n').encode())
    print(json.dumps({'artifact': str(output / 'solana_escrow.so'), 'sha256': sha(artifact), 'profile': profile}))


if __name__ == '__main__':
    main()
