// Copyright (c) 2021, The Talleo developers
// Copyright (c) 2021 - 2026, The Karbo developers
//
// This file is part of Karbo.
//
// Karbo is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Karbo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with Karbo. If not, see <http://www.gnu.org/licenses/>.

#ifdef WIN32
#include <windows.h>
#endif

#include <boost/program_options.hpp>
#include <fstream>
#include <string>
#include <vector>

#include "Common/CommandLine.h"
#include "Common/ColouredMsg.h"
#include "Common/StringTools.h"
#include "CryptoNoteCore/Currency.h"
#include "CryptoNoteCore/GenesisTreasuryReserve.h"
#include "PqAddress.h"
#include "crypto_pq/PqSeed.h"
#include "crypto/crypto-util.h"
#include "Logging/LoggerManager.h"
#include "Logging/LoggerRef.h"
#include "Mnemonics/electrum-words.h"
#include "CryptoNoteConfig.h"
#include "version.h"

#undef ERROR

using namespace CryptoNote;
using namespace Logging;

namespace po = boost::program_options;

namespace command_line
{
  const command_line::arg_descriptor<std::string> arg_file = {"file", "Specify the file name prefix to save generated keys to. "
    "Defaults to \"treasury-reserve-accounts\"."};
  const command_line::arg_descriptor<int> arg_treasury_reserve = {"treasury-reserve-accounts",
    "Generate N independent PQ accounts for the genesis Treasury Reserve: writes <file>.txt "
    "(mnemonics/secrets) and <file>.inc (GenesisTreasuryReserveKeys.inc with the public keys)", 0};
}

// Generate N independent PQ accounts for the genesis Treasury Reserve. Each account
// is a fresh CSPRNG master seed; its Electrum mnemonic is the recovery secret
// (load in simplewallet to recover). Public keys go into a committed
// GenesisTreasuryReserveKeys.inc; secrets go to a separate (gitignored) file.
bool generate_treasury_reserve_accounts(const po::variables_map& vm, Currency& currency) {
    int count = command_line::get_arg(vm, command_line::arg_treasury_reserve);
    std::string filePrefix = command_line::get_arg(vm, command_line::arg_file);
    if (filePrefix.empty()) filePrefix = "treasury-reserve-accounts";

    std::ofstream secrets(filePrefix + ".txt", std::ofstream::out | std::ofstream::trunc);
    if (!secrets) {
        std::cerr << WarningMsg("Cannot open secrets file " + filePrefix + ".txt") << std::endl;
        return false;
    }
    secrets << "# Discrete genesis Treasury Reserve recipient accounts — SECRET, keep offline.\n";
    secrets << "# " << count << " independent accounts. Load the mnemonic in simplewallet to recover.\n\n";

    std::vector<std::string> viewHex, spendHex;
    for (int i = 0; i < count; ++i) {
        // Generate a fresh 32-byte PQ master seed (same derivation path as the wallet).
        CryptoPQ::SeedMaster seed{};
        secure_random_bytes(seed.data(), seed.size());

        // Mnemonic = Electrum words of the raw seed bytes (same as simplewallet getSeed).
        std::string mnemonic, lang = "English";
        Crypto::SecretKey seedKey;
        std::memcpy(seedKey.data, seed.data(), sizeof(seedKey.data));
        Crypto::ElectrumWords::bytes_to_words(seedKey, mnemonic, lang);

        auto view  = CryptoPQ::deriveViewKeys(seed);
        auto spend = CryptoPQ::deriveSpendKeys(seed);

        CryptoNote::PqAddress addr =
            CryptoNote::makePqAddress(currency.publicAddressBase58Prefix(), view.first, spend.first);
        std::string pqAddr = CryptoNote::encodePqAddress(addr, CryptoNote::pqBech32Hrp(currency.isTestnet()));

        std::string vh = Common::toHex(view.first.data(),  view.first.size());
        std::string sh = Common::toHex(spend.first.data(), spend.first.size());
        viewHex.push_back(vh);
        spendHex.push_back(sh);

        secrets << "## Batch " << i << "\n";
        secrets << "mnemonic:      " << mnemonic << "\n";
        secrets << "pq_address:    " << pqAddr << "\n";
        secrets << "view_pub_hex:  " << vh << "\n";
        secrets << "spend_pub_hex: " << sh << "\n\n";
    }
    secrets.close();

    std::ofstream inc(filePrefix + ".inc", std::ofstream::out | std::ofstream::trunc);
    if (!inc) {
        std::cerr << WarningMsg("Cannot open include file " + filePrefix + ".inc") << std::endl;
        return false;
    }
    inc << "// AUTO-GENERATED by `admin-tools --treasury-reserve-accounts` — DO NOT EDIT BY HAND.\n";
    inc << "//\n";
    inc << "// Recipient PUBLIC keys for the genesis Treasury Reserve, one entry per batch.\n";
    inc << "// The matching mnemonics/secrets are NOT in the repo — see https://docs.discrete.cash/#/consensus/genesis.\n\n";
    inc << "static const char* const kGenesisTreasuryReserveViewPubHex[CryptoNote::GENESIS_TREASURY_RESERVE_BATCHES] = {\n";
    for (const auto& h : viewHex) inc << "  \"" << h << "\",\n";
    inc << "};\n\n";
    inc << "static const char* const kGenesisTreasuryReserveSpendPubHex[CryptoNote::GENESIS_TREASURY_RESERVE_BATCHES] = {\n";
    for (const auto& h : spendHex) inc << "  \"" << h << "\",\n";
    inc << "};\n";
    inc.close();

    std::cout << SuccessMsg("\nGenerated " + std::to_string(count) + " Treasury Reserve accounts.\n");
    std::cout << "  secrets: " << filePrefix << ".txt  (KEEP OFFLINE, do not commit)\n";
    std::cout << "  keys:    " << filePrefix << ".inc  (copy to src/CryptoNoteCore/GenesisTreasuryReserveKeys.inc)\n";
    return true;
}

int main(int argc, char** argv) {
    LoggerManager logManager;
    LoggerRef logger(logManager, "admin-tools");

    CurrencyBuilder builder(logManager);
    Currency currency = builder.currency();

    std::string coinName(CryptoNote::CRYPTONOTE_NAME);
    std::cout << InformationMsg(coinName + " admin tools v. " + std::string(PROJECT_VERSION)) << std::endl;

    try {
        po::options_description desc_cmd_only("Available command line options");

        command_line::add_arg(desc_cmd_only, command_line::arg_file);
        command_line::add_arg(desc_cmd_only, command_line::arg_treasury_reserve);
        command_line::add_arg(desc_cmd_only, command_line::arg_help);

        bool r = command_line::handle_error_helper(desc_cmd_only, [&]()
        {
            po::variables_map vm;
            po::store(po::parse_command_line(argc, argv, desc_cmd_only), vm);

            if (command_line::get_arg(vm, command_line::arg_treasury_reserve) > 0) {
                return generate_treasury_reserve_accounts(vm, currency);
            }

            std::cout << desc_cmd_only << std::endl;
            return true;
        });

        if (!r)
            return 1;
    } catch (const std::exception& e) {
        logger(Logging::ERROR, BRIGHT_RED) << "Exception: " << e.what();
        return 1;
    }
    return 0;
}
